name: ird_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  get: ^4.6.5
  dio: ^4.0.6
  easy_localization: ^3.0.1
  lazy_load_scrollview: ^1.3.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.23.0+1
  intl: ^0.17.0
  shared_preferences: ^2.0.17
  connectivity_plus: ^3.0.2
  google_fonts: ^4.0.1
  webview_flutter: ^2.0.4
  cached_network_image: ^3.2.3
  flutter_easyloading: ^3.0.5
  flutter_html: ^2.2.1
  autocomplete_textfield: ^2.0.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_typeahead: ^4.3.1
  table_calendar: ^3.0.8
  intl_phone_field: ^3.1.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.8
  group_button: ^5.2.2
  flutter_staggered_grid_view: ^0.6.2
  shimmer: ^2.0.0
  country_code_picker: ^2.0.2
  permission_handler: ^10.2.0
  flutter_gen_runner: ^5.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.5
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/locales/
    - assets/logos/